import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: { flex: 1, backgroundColor: "#FFFFFF" },
  scrollView: { flex: 1 },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    padding: 16,
    backgroundColor: "#FFFFFF",
    borderBottomWidth: 1,
    borderBottomColor: "#E0E0E0",
  },
  headerTitle: { fontSize: 18, fontWeight: "600", color: "#000000" },
  headerActions: { flexDirection: "row", gap: 12 },
  headerAction: { padding: 4 },
  icon: { fontSize: 20, color: "#000000" },
  sectionIcon: { fontSize: 20, color: "#000000" },
  buttonIcon: { fontSize: 20, color: "#FFFFFF", marginRight: 8 },
  imageContainer: { position: "relative" },
  carImage: { height: 256 },
  imageCounter: {
    position: "absolute",
    bottom: 16,
    left: 16,
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 4,
  },
  imageCounterText: { color: "#FFFFFF", fontSize: 14 },
  noImageText: {
    color: "#666666",
    fontSize: 16,
    textAlign: "center",
    padding: 16,
  },
  section: { padding: 16, borderTopWidth: 1, borderTopColor: "#E0E0E0" },
  ownerText: { color: "#4B4B4B", fontSize: 14 },
  carTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#000000",
    marginTop: 2,
  },
  carSubtitle: { color: "#4B4B4B", fontSize: 14, marginTop: 2 },
  ratingContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    marginTop: 4,
  },
  ratingScore: { fontSize: 18, fontWeight: "bold", color: "#000000" },
  ratingCount: { color: "#4B4B4B", fontSize: 14 },
  sectionTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#000000",
    marginBottom: 16,
  },
  tripRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
    gap: 8,
  },
  tripInfo: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
    flex: 1,
  },
  tripIcon: { fontSize: 20, marginTop: 2, color: "#000000" },
  tripLabel: { fontWeight: "600", color: "#000000", fontSize: 16 },
  tripDetail: { color: "#4B4B4B", fontSize: 14, marginTop: 2 },
  editIcon: {
    borderWidth: 1,
    borderColor: "#000000",
    borderRadius: 4,
    padding: 4,
    zIndex: 1,
  },
  editIconText: { color: "#000000", fontSize: 16 },
  deluxeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  deluxeDescription: {
    color: "#4B4B4B",
    fontSize: 14,
    marginTop: 4,
    lineHeight: 20,
  },
  featuresGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    marginBottom: 12,
  },
  featureChip: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    minWidth: "45%",
  },
  featureChipSingle: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#F5F5F5",
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: 8,
    gap: 8,
    alignSelf: "flex-start",
  },
  featureIcon: { fontSize: 16, color: "#000000" },
  featureText: { color: "#000000", fontSize: 14 },
  listContainer: { gap: 12 },
  listItem: { color: "#666666", fontSize: 16 },
  noDataText: { color: "#666666", fontSize: 14 },
  subsectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 12,
    marginTop: 8,
  },
  featureList: { gap: 16, marginBottom: 24 },
  featureItem: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  featureItemContent: { flex: 1 },
  featureItemTitle: {
    fontWeight: "500",
    color: "#000000",
    fontSize: 16,
    lineHeight: 22,
  },
  featureItemDesc: {
    color: "#4B4B4B",
    fontSize: 14,
    marginTop: 2,
    lineHeight: 20,
  },
  overallRating: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 16,
  },
  overallRatingScore: { fontSize: 24, fontWeight: "bold", color: "#000000" },
  overallRatingCount: { color: "#4B4B4B", fontSize: 16 },
  ratingsBreakdown: { gap: 12, marginBottom: 16 },
  ratingRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  ratingCategory: { color: "#666666", fontSize: 16 },
  ratingBarContainer: { flexDirection: "row", alignItems: "center", gap: 8 },
  ratingBarBg: {
    width: 128,
    height: 8,
    backgroundColor: "#E0E0E0",
    borderRadius: 4,
  },
  ratingBarFill: {
    width: "100%",
    height: "100%",
    backgroundColor: "#000000",
    borderRadius: 4,
  },
  ratingValue: { color: "#000000", fontSize: 14, minWidth: 24 },
  ratingsNote: { color: "#4B4B4B", fontSize: 14, marginBottom: 16 },
  reviewsScroll: { marginBottom: 8 },
  reviewCard: {
    backgroundColor: "#FAFAFA",
    borderRadius: 8,
    padding: 16,
    marginRight: 16,
    width: 280,
  },
  reviewHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginBottom: 8,
  },
  avatar: {
    width: 32,
    height: 32,
    backgroundColor: "#B0B0B0",
    borderRadius: 16,
  },
  reviewerName: { fontWeight: "500", color: "#000000", fontSize: 14 },
  reviewDate: { color: "#4B4B4B", fontSize: 12 },
  starsContainer: { flexDirection: "row", gap: 2, marginBottom: 8 },
  reviewText: { color: "#666666", fontSize: 14, lineHeight: 20 },
  seeAllReviews: {
    color: "#000000",
    fontSize: 14,
    fontWeight: "500",
    marginTop: 8,
  },
  hostContainer: { flexDirection: "row", alignItems: "center", gap: 12 },
  hostImageContainer: { position: "relative" },
  hostImage: { width: 60, height: 60, borderRadius: 30 },
  hostRating: {
    position: "absolute",
    bottom: -4,
    right: -4,
    backgroundColor: "#F5F5F5",
    borderRadius: 12,
    paddingHorizontal: 8,
    paddingVertical: 2,
    flexDirection: "row",
    alignItems: "center",
    gap: 2,
  },
  hostRatingText: { color: "#000000", fontSize: 12 },
  hostName: { fontWeight: "bold", color: "#000000", fontSize: 18 },
  hostInfo: { color: "#4B4B4B", fontSize: 14 },
  rulesList: { gap: 16 },
  ruleItem: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  ruleTitle: { fontWeight: "500", color: "#000000", fontSize: 16 },
  ruleDesc: { color: "#4B4B4B", fontSize: 14, marginTop: 2, lineHeight: 20 },
  policyItem: { flexDirection: "row", alignItems: "flex-start", gap: 12 },
  policyTitle: { fontWeight: "500", color: "#000000", fontSize: 16 },
  policyDesc: { color: "#4B4B4B", fontSize: 14, marginTop: 2, lineHeight: 20 },
  insuranceHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  insuranceInfo: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
  },
  insuranceProvider: { color: "#4B4B4B", fontSize: 14 },
  bottomPadding: { height: 80 },
  bottomBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: "#FFFFFF",
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  totalPrice: { fontSize: 20, fontWeight: "bold", color: "#000000" },
  continueButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#000000",
    borderRadius: 8,
    paddingHorizontal: 32,
    paddingVertical: 12,
  },
  continueButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "600" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "flex-end",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#FFFFFF",
    borderTopLeftRadius: 16,
    borderTopRightRadius: 16,
    padding: 24,
    width: "100%",
    maxHeight: "80%",
  },
  modalHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 24,
  },
  modalTitle: { fontSize: 20, fontWeight: "700", color: "#000000" },
  modalCloseIcon: { fontSize: 28, color: "#000000" },
  modalSection: { marginBottom: 24 },
  modalSubtitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#000000",
    marginBottom: 12,
  },
  pickerContainer: {
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    backgroundColor: "#F5F5F5",
  },
  picker: {
    color: "#000000",
    fontSize: 16,
  },
  confirmButton: {
    backgroundColor: "#000000",
    borderRadius: 8,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 16,
  },
  confirmButtonText: { color: "#FFFFFF", fontSize: 16, fontWeight: "600" },
  datePicker: { width: "100%", height: 200, marginBottom: 16 },
  dateSummary: { marginBottom: 16 },
  dateSummaryText: { fontSize: 16, color: "#000000", marginBottom: 8 },
  dateEditButtons: { flexDirection: "row", gap: 8, marginTop: 12 },
  editDateButton: {
    backgroundColor: "#F5F5F5",
    borderRadius: 8,
    paddingVertical: 12,
    paddingHorizontal: 16,
    alignItems: "center",
    flex: 1,
  },
  editDateButtonText: { color: "#000000", fontSize: 16, fontWeight: "600" },
  errorText: { color: "#FF0000", fontSize: 14, marginBottom: 12 },
  disabledButton: { backgroundColor: "#B0B0B0" },
  insuranceContent: { maxHeight: "60%" },
  insuranceText: { color: "#4B4B4B", fontSize: 14, lineHeight: 20 },
  webDateContainer: { gap: 16 },
  webDateField: { marginBottom: 16 },
  webDateLabel: { fontSize: 16, color: "#000000", marginBottom: 8 },
  webDateInput: {
    padding: 8,
    borderWidth: 1,
    borderColor: "#E0E0E0",
    borderRadius: 8,
    fontSize: 16,
    width: "100%",
  },
  vehicleDetails: { gap: 12 },
  vehicleDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  vehicleDetailLabel: { fontSize: 16, fontWeight: "500", color: "#000000" },
  vehicleDetailValue: { fontSize: 16, color: "#4B4B4B" },
});